[package]
name = "pegasus_graph"
version = "0.1.0"
authors = ["chenqiang.mcq <chenqiang.mcq@alibaba-inc.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.0"
nohash-hasher = "0.2.0"
#snap = "1"
rand = "0.8.3"
memmap = "0.7.0"
ahash = "0.7.2"
lazy_static = "1.3.0"
klickhouse = "0.2"
futures = "0.3.19"
tonic = "0.5"
prost = "0.8"
tokio = { version = "1.0", features = ["macros", "sync", "rt-multi-thread"] }
pegasus_common = { path = "../common" }
futures-util = "0.3.19"

[dev-dependencies]
structopt = "0.3"

[build-dependencies]
tonic-build = "0.5"

[features]
default = []
gcip = []